In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
sns.set()

In [5]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()  

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [8]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [13]:
feature = data[['SAT','Rand 1,2,3']]
feature 


SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [15]:
target = data['GPA']

In [17]:
reg = LinearRegression()

In [19]:
reg.fit(feature,target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.score(feature,target)

0.4066811952814285

In [21]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [22]:
reg.intercept_

0.29603261264909486

In [24]:
reg.score(feature,target)

0.4066811952814285

### Formula for Adjusted $R^2$
$ R^2_{adj.} = 1 - (1-R^2) *\frac{n-1}{n-p-1}$


In [27]:
feature.shape

(84, 2)

In [31]:
r2 = reg.score(feature,target)
n = feature.shape[0]
p = feature.shape[1]

In [57]:
adjR = 1-(n-1)/(n-p-1)*(1-r2)

In [59]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler = StandardScaler()

In [63]:
scaler.fit(feature)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [69]:
feature_scaled = scaler.transform(feature)

In [71]:
reg = LinearRegression()

In [72]:
reg.fit(feature_scaled,target)
reg.coef_
reg.intercept_

3.330238095238095

In [73]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [81]:
reg_summary = pd.DataFrame([['Bais'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [83]:
reg_summary

Features   Weights
0        Bais  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [86]:
newData = pd.DataFrame(data=[[1700,2],[1800,1]], columns= ['SAT','Rand 1,2,3'])

In [87]:
newData

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [88]:
new_data_scaled = scaler.transform(newData)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [89]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

In [92]:
reg_simple = LinearRegression()
x_simple_martrix = feature_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_martrix,target)
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])